config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'

  get 'home/notes', as: "notes"

  get 'home/classroom', ad: "classroom"

  get 'home/notice_board'

  resources :complaints

  get 'dashboard/index'

  get 'dashboard/complaint'

  get 'dashboard/notes'

  get 'dashboard/settings'

  resources :notes

  devise_for :admins
  devise_for :faculties
  devise_for :students

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/complaint_type.rb
class ComplaintType < ActiveRecord::Base
end

app/models/complainttype.rb
class Complainttype < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base

  has_many :subjects
  has_many :notes
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader

  belongs_to :faculty
  belongs_to :subject
  belongs_to :department
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/models/subject.rb
class Subject < ActiveRecord::Base


  belongs_to :department
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:regno, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:regno, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:regno, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @complaints = Complaint.all
    respond_with(@complaints)
  end

  def show
    respond_with(@complaint)
  end

  def new
    @complaint = Complaint.new
    respond_with(@complaint)
  end

  def edit
  end

  def create
    @complaint = Complaint.new(complaint_params)
    @complaint.save
    respond_with(@complaint)
  end

  def update
    @complaint.update(complaint_params)
    respond_with(@complaint)
  end

  def destroy
    @complaint.destroy
    respond_with(@complaint)
  end

  private
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    def complaint_params
      params.require(:complaint).permit(:title, :description, :department_id, :complainttype_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index


    if admin_signed_in?
      
    end
  end

  def complaint
  end

  def notes
  end

  def settings
  end
end

app/controllers/fauculty_dashboard_controller.rb
class FaucultyDashboardController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  

  	
  end

  def notes
  end

  def classroom
  end

  def notice_board
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @notes = Note.all
    respond_with(@notes)
  end

  def show
    respond_with(@note)
  end

  def new
    if faculty_signed_in?
    @note = Note.new
    respond_with(@note)
  else

    redirect_to new_faculty_session_path
    end

  end

  def edit
  end

  def create
    if faculty_signed_in?

      @note = Note.new(note_params)
      @note.attachment = params[:file]
      @note.faculty = current_faculty
      @note.save
      respond_with(@note)
    end
  end

  def update
    @note.update(note_params)
    respond_with(@note)
  end

  def destroy
    @note.destroy
    respond_with(@note)
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :description, :subject_id, :faculty_id, :department_id, :attachment )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fauculty_dashboard_helper.rb
module FaucultyDashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/complaints/_form.html.erb
<%= form_for(@complaint) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :complainttype_id %><br>
    <%= f.number_field :complainttype_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Department</th>
      <th>Complainttype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.title %></td>
        <td><%= complaint.description %></td>
        <td><%= complaint.department_id %></td>
        <td><%= complaint.complainttype_id %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @complaint.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @complaint.description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @complaint.department_id %>
</p>

<p>
  <strong>Complainttype:</strong>
  <%= @complaint.complainttype_id %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/dashboard/complaint.html.erb
<h1>Dashboard#complaint</h1>
<p>Find me in app/views/dashboard/complaint.html.erb</p>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/notes.html.erb
<h1>Dashboard#notes</h1>
<p>Find me in app/views/dashboard/notes.html.erb</p>

app/views/dashboard/settings.html.erb
<h1>Dashboard#settings</h1>
<p>Find me in app/views/dashboard/settings.html.erb</p>

app/views/home/classroom.html.erb
<h1>Home#classroom</h1>
<p>Find me in app/views/home/classroom.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/notes.html.erb
<h1>Home#notes</h1>
<p>Find me in app/views/home/notes.html.erb</p>

app/views/home/notice_board.html.erb
<h1>Home#notice_board</h1>
<p>Find me in app/views/home/notice_board.html.erb</p>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.collection_select(:subject_id, Subject.all, :id, :code) %>
    </div>

  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.collection_select(:department_id, Department.all, :id, :name) %>
  </div>

  <%= f.file_field :attachment %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Subject</th>
      <th>Faculty</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.description %></td>
        <td><%= note.subject_id %></td>
        <td><%= note.faculty_id %></td>
        <td><%= note.department_id %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @note.subject.title %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @note.faculty.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @note.department.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @note.attachment.url %>
</p>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>