config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'

  get 'home/notes', as: "notes"

  get 'home/classroom', ad: "classroom"

  get 'home/notice_board'

  resources :complaints

  get 'dashboard/index'

  get 'dashboard/complaint'

  get 'dashboard/notes'

  get 'dashboard/settings'

  resources :notes

  devise_for :admins
  devise_for :faculties
  devise_for :students

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/complaint_type.rb
class ComplaintType < ActiveRecord::Base
end

app/models/complainttype.rb
class Complainttype < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base

  has_many :subjects
  has_many :notes
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader

  belongs_to :faculty
  belongs_to :subject
  belongs_to :department
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/models/subject.rb
class Subject < ActiveRecord::Base


  belongs_to :department
  has_many :notes
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @complaints = Complaint.all
    respond_with(@complaints)
  end

  def show
    respond_with(@complaint)
  end

  def new
    @complaint = Complaint.new
    respond_with(@complaint)
  end

  def edit
  end

  def create
    @complaint = Complaint.new(complaint_params)
    @complaint.save
    respond_with(@complaint)
  end

  def update
    @complaint.update(complaint_params)
    respond_with(@complaint)
  end

  def destroy
    @complaint.destroy
    respond_with(@complaint)
  end

  private
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    def complaint_params
      params.require(:complaint).permit(:title, :description, :department_id, :complainttype_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index


    if admin_signed_in?
      
    end
  end

  def complaint
  end

  def notes
  end

  def settings
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  

  	
  end

  def notes
  end

  def classroom
  end

  def notice_board
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @notes = Note.all
    respond_with(@notes)
  end

  def show
    respond_with(@note)
  end

  def new
    if faculty_signed_in?
    @note = Note.new
    respond_with(@note)
  else

    redirect_to new_faculty_session_path
    end

  end

  def edit
  end

  def create
    if faculty_signed_in?

      @note = Note.new(note_params)
      @note.attachment = params[:file]
      @note.faculty = current_faculty
      @note.save
      respond_with(@note)
    end
  end

  def update
    @note.update(note_params)
    respond_with(@note)
  end

  def destroy
    @note.destroy
    respond_with(@note)
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :description, :subject_id, :faculty_id, :department_id, :attachment )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fauculty_dashboard_helper.rb
module FaucultyDashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SsipNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if student_signed_in? %>
<%= render "shared/header_student" %>
<%end %>
<%= yield %>

</body>
</html>

app/views/shared/_header_student.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Notes", notes_path %></li>
        <li><%= link_to "Classroom", notes_path %></li>
       
        </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">

           <% if student_signed_in? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_student.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">

            <li><%= link_to "Logout", destroy_student_session_path, :method => "DELETE" %></li>
            <li><%= link_to "Profile", destroy_student_session_path %></li>
            <li><%= link_to "Edit", edit_student_registration_path %></li>

          </ul>
        </li>
           <% else %>
            <li><%= link_to "Login", new_student_session_path %></li>

           <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>